services:
  db:
    image: postgres:16-alpine
    container_name: inspectpro-db
    environment:
      POSTGRES_DB: inspectpro
      POSTGRES_USER: inspectpro
      POSTGRES_PASSWORD: inspectpro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inspetpro"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: inspectpro-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/inspectpro
      SPRING_DATASOURCE_USERNAME: inspectpro
      SPRING_DATASOURCE_PASSWORD: inspectpro
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 900000
      JWT_REFRESH_EXPIRATION: 604800000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data: