ALTER TABLE users
    ALTER COLUMN role TYPE VARCHAR(50);

ALTER TABLE profiles
    ALTER COLUMN type TYPE VARCHAR(50);

ALTER TABLE credentials
    ALTER COLUMN type TYPE VARCHAR(50),
    ALTER COLUMN status TYPE VARCHAR(50);

ALTER TABLE subscriptions
    ALTER COLUMN tier TYPE VARCHAR(50);